name: Auto Deploy

on:
  push:
    branches:
      - main   # 你开发用的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Setup Git user
        run: |
          git config --global user.name ruth8
          git config --global user.email 1256434196@qq.com

      - name: Deploy to GitHub Pages
        run: npm run deploy